engines:
 pmdjava:
   enabled: true
   exclude_paths:
     - config/engines.yml
     - **/*.sql
 duplication:
   enabled: true
   exclude_paths:
     - config/engines.yml
     - **/*.sql
 metrics:
   enabled: true
   exclude_paths:
     - config/engines.yml
     - **/*.sql
 coverage:
   enabled: true
   exclude_paths:
    - config/engines.yml
    - **/config/**
    - **.sql
    - **/*.yml
    - **/*.xml
    - **/*.gitignore
    - **/*.xhtml
    - **/*.properties
